### ISSUE TITLE
Powershell colorscheme doesn't get updated by colortool.

### ISSUE THREAD

**Issue by artifaktor** [Microsoft/console#131]
It looks like one can run two different kind of powershell, one with the normal way of launching it from the start, or from the win+x menu, and one with the right click open powershell here method. The normal ps colorscheme doesn't get update by the colortool while the cmd console, and the wsl console do get the new colorscheme. Here is a screenshot of this happening:
![kepernyofelvetel 2](https://user-images.githubusercontent.com/8431047/37311340-2e286164-2647-11e8-883f-0c3608d521b5.png)

**Comment by zadjii-msft** [comment]
That's because these *are* different mechanisms by which you can launch powershell. One involves the Start Menu's Powershell shortcut, and the other uses the registry's values for powershell.exe. Colortool will only be able to set the values for the version that was launched, the other will remain unmodified. 

See [this blog post ](https://blogs.msdn.microsoft.com/commandline/2017/06/20/understanding-windows-console-host-settings/) for details.

**Comment by artifaktor** [comment]
I see, thank you for the link and the information about settings mechanism. I would never have guessed that this was the reason for the behaviour, because I did not modify the setting for that shortcut, I didn't think it would retain those settings. This was really helpfull.
