### ISSUE TITLE
Don't stop CUI apps when selecting area, just stop rendering only when determining selected area

### ISSUE THREAD

**Issue by tats-u** [Microsoft/console#152]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.16299.371

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
run CUI apps in Windows Console

* What's wrong / what should be happening instead:
They sometimes stop running.  they resume when **the Enter key is pressed.**

**Comment by zadjii-msft** [comment]
Both Ctrl+S and selecting text will pause the console output - have you pressed Ctrl+S or selected any text? It's pretty easy to accidentally activate the selection, if the window is already the foreground window and you click on it, it'll start the selection. You can tell if the console is in select mode because the titlebar will prepend "Select" to the rest of the title.

![image](https://user-images.githubusercontent.com/18356694/38746569-c45055d4-3efc-11e8-986a-b9c54ce6c77e.png)

**Comment by tats-u** [comment]
That's it.  Selecting text in the console stops apps.

However, I suppose no terminal emulator other than Windows Console (e.g. mintty) stops apps even when choosing selected area has been done.  Apps resume running when dragging has been finished.

**Comment by zadjii-msft** [comment]
This is definitely one of those "can't change it because that's how it's always worked" kind of situations. If we change this behavior, then suddenly the issue is "Why doesn't selecting the console pause output anymore?"

Would I love to have this be a configurable setting? Absolutely!

Is this going to be a high enough priority to *ever* get on my plate? Unlikely :/

**Comment by tats-u** [comment]
I'll wait for the new option and look into the behavior of GNOME terminal.  It doesn't stop at least after drag for selecting, I suppose, though.

**Comment by tats-u** [comment]
I looked into the behavior of PuTTY and MobaXterm by executing `while true; do date; sleep 1; done`, and they are both:

- selecting (more than 2 seconds): just stopped **rendering**, not stopping processes because mouse 
- selected: resumed rendering

I found they doesn't stop processes at all.  I'll look into the rendering GNOME terminal later, but I suppose it is only Windows Console that stop processes.

**Comment by tats-u** [comment]
Output in WSL in Windows Console:

```
Sat Apr 14 14:00:15 DST 2018
Sat Apr 14 14:00:16 DST 2018
Sat Apr 14 14:00:17 DST 2018
Sat Apr 14 14:00:18 DST 2018
Sat Apr 14 14:00:20 DST 2018
Sat Apr 14 14:00:21 DST 2018
Sat Apr 14 14:00:35 DST 2018
Sat Apr 14 14:00:36 DST 2018
Sat Apr 14 14:00:37 DST 2018
Sat Apr 14 14:00:38 DST 2018
^C
```

Both third-party terminal simulators didn't skip seconds at all.

**Comment by tats-u** [comment]
There is a similar feedback on wpdev.uservoice.com:
https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/31941592-selecting-text-shouldn-t-pause-program

**Comment by bitcrazed** [comment]
As @zadjii-msft said, this has been Console's behavior for 30+ years and is depended upon by MANY users.

We'll consider making this optional in the future, but don't hold your breath 😜
