### ISSUE TITLE
WSL tmux screen scrambled by launching powershell.exe

### ISSUE THREAD

**Issue by agowa338** [Microsoft/console#155]
### Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.371]

### What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

 * Open Cmd
 * `bash`
 * `apt-get update`
 * `apt-get install tmux`
 * `tmux`
 * [CTRL] + [B]
 * [Shift] + [5]
 * `powershell.exe`
 * `Clear-Host`
Now the screen separation is gone, but if you press [STRG] + [B]; [Arrow Left] it still switches to the console on the left, but the screen is garbage. But if you only use linux applications (those inside wsl) it works fine.

The thing actually gets worse if the hosting shell is powershell, e. g. you used powershell.exe to run the bash command. Then also normal linux applications inside wsl destroy the screen separation.

### What's wrong / what should be happening instead:
The screen layout should not get destroyed when launching applications.
Also cmd.exe and powershell should have the same behavior after executing the bash command e. g. switching into wsl.

**Comment by zadjii-msft** [comment]
Running Windows executables in WSL is really buggy before 17617. Everything you described was due to how interop was first implemented, however, on newer Insider's builds this should already be fixed!
![image](https://user-images.githubusercontent.com/18356694/38822573-b6d1a968-4158-11e8-9b60-9a9b2ede970c.png)
