### ISSUE TITLE
colortool's 'solarized_dark' theme makes some characters unreadable

### ISSUE THREAD

**Issue by mikemaccana** [Microsoft/console#180]
## Your Windows build number:  (Type `ver` at a Windows Command Prompt)

  [Environment]::OSVersion

    Platform ServicePack Version      VersionString
    -------- ----------- -------      -------------
    Win32NT             10.0.17666.0 Microsoft Windows NT 10.0.17666.0

I don't run command prompt because it's not Windows NT 4. 

## What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

Using https://github.com/Microsoft/console/releases/download/1708.14008/colortool.zip

     ./colortool -b solarized_dark

![image](https://user-images.githubusercontent.com/172594/40107604-9c09f36a-58f0-11e8-96bf-d359edb121ec.png)

The '..' in 'cd..' is close to invisible. If you look very closely above, you can see there's two dark blue dots on the dark green background, but you wouldn't see them otherwise.

## What's wrong / what should be happening instead:

The blue should be a little lighter than the background.

**Comment by zadjii-msft** [comment]
@miniksa is exactly right here. You'll notice that even the [mbadolato/iTerm2-Color-Schemes](https://github.com/mbadolato/iTerm2-Color-Schemes) repo has **5** different Solarized schemes in it, and IIRC we took it from one of their schemes.

![image](https://user-images.githubusercontent.com/18356694/40128802-73f98236-58e7-11e8-84e8-47c2ea521aac.png)

The default `solarized_dark` looks like this: 
![image](https://user-images.githubusercontent.com/18356694/40129105-48b0d07e-58e8-11e8-8bf1-9c28c0065212.png)

I have a (local) patched version that looks like this:
![image](https://user-images.githubusercontent.com/18356694/40129124-5934e0b6-58e8-11e8-9f8e-c87d1cf8b198.png)
 
Mainly I switched out the BRIGHT_BLACK with a different gray, and for all the bright colors that were just various shades of gray, I replaced them with the color they have for the dark version of the color. [Solarized](http://ethanschoonover.com/solarized) doesn't really give you that many color options to work with.

Also note at the bottom, `cd ..` much more visible then before (still not great, but hey, I'm sure that can be fixed with a psreadline configuration setting to not have it be BRIGHT_BLACK on DARK_BLACK)

I can make a PR to add that scheme if that seems good.

**Comment by mikemaccana** [comment]
Hey @miniksa! Sorry, I didn't mean to be snarky about `ver`, just thought it was funny since I assume everyone in https://github.com/Microsoft/console (and most other Windows command line people besides) would be running Powershell 😀. 

PR incoming 👍

**Comment by zadjii-msft** [comment]
lol almost everyone on the console team uses cmd, not powershell

**Comment by mikemaccana** [comment]
@zadjii-msft Mike I'm very disappointed. 😉 Thanks to you all for colortool it's rad.

**Comment by M-Pixel** [comment]
It appears that this issue has regressed, and should be re-opened.  Version 0.10.781.0 from the Windows Store has invisible -Args in PS6 on Solarized Dark, invisible numbers in PS6 on Solarized Light.

**Comment by DHowett-MSFT** [comment]
The bug you’re commenting on is about ColorTool, not Windows Terminal. It categorically cannot have regressed, because it was resolved almost a year before Terminal even existed. :smile:

**Comment by M-Pixel** [comment]
@DHowett-MSFT your pedantic comment is unhelpful and appears to serve no end other than mocking my lack of understanding of the role of ColorTool within this application.  If you would care to explain what ColorTool is/was and how it is/isn't related to the current Solarized Dark theme in this application, or indicated that other issues were a more appropriate forum, that would have been more helpful than mansplaining and laughing.

I'll move along over to #4047
