### ISSUE TITLE
Console used as a WSL terminal has garbled screen on paging

### ISSUE THREAD

**Issue by nicferrier** [Microsoft/console#210]
The console as a WSL terminal looks broken in the latest builds; I'm on Windows Insider and have build:

    17692.red_prerelease.180609.1317

ver output shows:

    Microsoft Windows [Version 10.0.17692.1000]

Steps to recreate:

* open a bash terminal, say, ubuntu 16 or 18
* view a file, eg:
    
      view .bashrc

* cursor down a page of lines, so the terminal has to scroll
* see the screen garble and all the lines get compressed to the bottom line

      TERM reports xterm-256color

View is just one way to validate, I haven't been able to narrow it down but many things that do sophisticated screen are failing.

* ls -l works
* htop works
* less -r works
* emacs -nw works
* view doesn't work
* vi doesn't work
* vi doesn't work in a remote ssh from the terminal
* tmux doesn't work

Steps to test tmux:

* `apt-get install tmux`
* `tmux new-session`
* `ls -la`
* see the results are garbled at the bottom line

I'm not sure when this broke as I haven't used it that much in the past week.

Any help?

**Comment by JoBrad** [comment]
This is also happening for me, on Windows 10 build 17692. . I've posted a video of the behavior I'm seeing here: https://imgur.com/a/24bMNoc.

**Comment by mkarpoff** [comment]
It is still an issue in Windows 10 build 17704

**Comment by nicferrier** [comment]
Actually I'm pretty sure this is not limited to a WSL shell. It's happening with a standard CMD console as well.

**Comment by nicferrier** [comment]
No response though. :-(

**Comment by alecacco** [comment]
Byt hey they fixed Ctrl+s shortcut in notepad! :D

Il giorno dom 1 lug 2018 alle ore 13:00 Nic Ferrier <
notifications@github.com> ha scritto:

**Comment by miniksa** [comment]
This is MSFT:17807270. It just hit the main branch in 17709 and should be fixed in Insiders shortly.

Sorry, we have several people on vacation the last few weeks and scrubbing GitHub has been a lower priority while we're low on people.

**Comment by JoBrad** [comment]
@miniksa Thanks for the follow-up! Appreciate it!

**Comment by nicferrier** [comment]
Yeah. I was trying not to be snarky. I didn't feel snarky. Y'all doing an impressive job of moving this stuff that hasn't moved for years.

**Comment by nicferrier** [comment]
Yep. That fixed it. Thanks!

**Comment by toloveru** [comment]
Any update on this issue and its resolution? In Fast ring it still seems to be present, and makes the WSL terminal pretty much useless.

**Comment by twisty** [comment]
@toloveru https://github.com/Microsoft/console/issues/210#issuecomment-401852104 states this is fixed in 17709. I can confirm that things got back-to-normal for me in 17711. Once you manage to upgrade to a post-17709 version you should be happy.

If you suspect that you can't update because you "disabled Telemetry in the Registry" you should open a new issue for that.

**Comment by toloveru** [comment]
Still struggling with the extent that Windows 10 included its data collection crap into this shitty system at this point. Reinstalled (because resetting which deleted all apps - because that's obviously where the issue is, right?! - didn't solve jack shit!), and it seems like Windows can't provide common drivers even for its stock system and USB keyboards as well as common Ethernet adapters. So I'm unable to monitor the network traffic with Wireshark that Windows uses to phone home initially. Thanks Microshaft! Phoning home piece of trash!

Yes I'm salty here. And no I don't regret it. I've spent so much time on an OS that I didn't want to use in the first place.. I don't care if you will inherit this platform GitHub and will become able to handle this account at will anymore. FUCK YOU MICROSHAFT! I wanted to go to sleep many hours ago. Instead I have to deal with your dystopian shit that I didn't even want to deal with at all in the first place. If only I could've installed Linux on this thing, I so fucking would've done it. If only it wasn't for fucking Nvidia.. you can bet your fucking ass on that!

**Comment by toloveru** [comment]
@twisty I know I should, but do you really think that an issue like this including accusations won't be closed just like that and swept under the rug? Apologies for littering this issue, but 1) Microsoft's response has been shit so far and 2) I'm prepared to lose this account. I've already migrated most stuff to GitLab and followers should be easy to rebuild - not that that's a primary purpose of Git in the first place though. At this point I just want to make it loud and clear that Microsoft clearly went for the 1984 future. I hate it. Many people should hate it. Microsoft went the shaft-route more than ever before.

**Comment by miniksa** [comment]
I see this fix in the Windows Insiders builds 17711 and higher like @twisty says.

@toloveru, it should be fixed if you update.
If you have concerns about privacy and the data being collected, I recommend you view https://privacy.microsoft.com/en-US/windows-10-feedback-diagnostics-and-privacy or check out the data we have connected to you personally at https://account.microsoft.com/privacy/ and delete it if you like.

I highly doubt someone is intentionally blocking you from updating if you have tinkered with the assorted telemetry registry keys. It just might be that one of the registry keys you disabled also stopped our ability to send back what OS version you are on or the configuration hardware of your machine so we know which build of Windows to send you. I'm not on that team, however, I just know a lot of our "telemetry pipelines" are shared utilities by a bunch of OS components which probably include the updater services.

**Comment by toloveru** [comment]
@miniksa I realize that this strongly deviates from OP's issue but I don't think that telemetry should be as tightly integrated with the OS as seems to be the case right now. I don't want to send out data about my OS usage at all other than the critical stuff such as e.g. build number and other non-personal stuff upon explicit request by clicking "Update" or periodically as in every day instead of multiple JSON requests to Microsoft per second. If not intentional, it'd be a really bad design. Adding a key (HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection - AllowTelemetry 0) and disabling the Connected User Experiences and Telemetry service shouldn't somehow stop updates from being applied.

As for me, I ended up having to reinstall the OS. Back to stable and contemplated my choice of becoming a telemetry subject in Insiders, just for the dark theme in Windows Explorer. Great and long-awaited feature, but not worth discarding basic privacy rights for. Turns out though that even with Basic telemetry the system still ends up making multiple requests per second for every driver update, app launch or whatever. If only I could make this bloody OS shut up and stop abusing my privacy. Then again, super tight integration, and thanks to Nvidia no option to run Linux like I do everywhere else. Thanks Microsoft!
