### ISSUE TITLE
Possible ANSI bug that surfaces in Docker/ConEmu

### ISSUE THREAD

**Issue by edrevo** [Microsoft/console#231]
After reading your [Windows Command Line post series](https://blogs.msdn.microsoft.com/commandline/2018/06/20/windows-command-line-backgrounder/), I think that these two bugs: https://github.com/Maximus5/ConEmu/issues/958 and https://github.com/moby/moby/issues/28814, which seem to be bouncing off between the moby and ConEmu projects, might actually be a bug in conhost.

The bug repro is dead simple: open up ConEmu and type `echo 'FROM hello-world' | docker build -t temp -`. This will fail because docker assumes ConEmu has ANSI support (https://github.com/moby/moby/blob/28cca5dcaa2aa21123805d7f2d51916ea1f38d71/pkg/term/term_windows.go#L74-L79), which I'm guessing actually happens in conhost as per this image:

![](https://msdnshared.blob.core.windows.net/media/2018/08/command-line-console-internals-800x455.png)

I can repro this on `Microsoft Windows [Versión 10.0.17134.112]`

**Comment by parkovski** [comment]
Just looked at this quickly, I’d guess the bug is in https://github.com/moby/moby/blob/master/pkg/term/windows/console.go

They return true for IsConsole if it is wrapper in an ANSI reader. If the underlying handle is a pipe and not a direct console handle and you call PeekConsoleInput, you’ll get the error you’re seeing. This looks like it only happens under ConEmu or ConsoleZ when input is piped based on the snippet you linked to.

**Comment by zadjii-msft** [comment]
Considering this seems to be a bug in moby, not conhost, I'm gonna close this as external.
