### ISSUE TITLE
Number of colors when console used in VSCode

### ISSUE THREAD

**Issue by bardware** [Microsoft/console#254]
Hello,

I noticed a behaviour regarding the number of available colors in the console in Windows 10
I work with Adobe ColdFusion. There's a 3rd party tool [Commandbox](https://www.ortussolutions.com/products/commandbox) that allows to run various CFML engines in one folder.
This tool is a single `.exe` files and requires Java.
I open `cmd`, start this exe and call `system-colors` to list all available colors.
This looks like
![grafik](https://user-images.githubusercontent.com/802702/45501629-0b6b1a00-b782-11e8-843e-fb0c1d2674f7.png)

Then I start VSCode editor and have `cmd` set up as default console.
When I start `box` there and call `system-colors` it looks like
![grafik](https://user-images.githubusercontent.com/802702/45501700-37869b00-b782-11e8-86cf-c9ae11e68fbc.png)

I wonder why this happens. Does it have to do with the console or with VSCode?

**Comment by zadjii-msft** [comment]
Well, this is *technically* the console's fault, but this is what we'd expect to happen.

VsCode's terminal is powered by winpty, which uses the Console API to query the contents of the output buffer, including both the characters and what their attributes (colors) are. Traditionally, the console only supported 16 colors, so the API can only return back 16 color values.

A couple years back we added support for full colors in the console (including 256 colors). However, we couldn't really change the console API, so we still could only return one of 16 colors when the app uses 256 color. We essentially round the 256 colors to their nearest equivalent in the 16 color table, so that the output via the API at least looks somewhat sane.

That explains the 256 colors part of the output in vscode. I'd presume that the color scheme you're using in vscode just re-uses each of the colors as both the dark and bright version of the color, which would explain why olive looks the same as yellow (for example).

**Comment by bitcrazed** [comment]
Thanks for posting @bardware. Closing since there's no follow-up action here.
