### ISSUE TITLE
Investigate apparent WinPTY issue with RS5/19H1 builds

### ISSUE THREAD

**Issue by miniksa** [Microsoft/console#270]
See https://github.com/Microsoft/vscode/issues/57803

**Comment by miniksa** [comment]
Tracked internally assigned to me as MSFT:19205200

**Comment by miniksa** [comment]
Good news! I found the commit ID that changed the behavior. Yay bisect! Still digging.

**Comment by Tyriar** [comment]
@miniksa did you end up finding a fix?

**Comment by miniksa** [comment]
I found it was @zadjii-msft's fault and I passed the buck to him. >__>

But he has a fix in PR right now. It's on my queue to read this morning.

**Comment by warpdesign** [comment]
Will the fix make it to October 2018 update or do we have to wait for the next big update in 6 months or so?

**Comment by warpdesign** [comment]
@zadjii-msft ok, thanks for the info. I'm not afraid if insiders but my Surface Book already had lots of problems with the stable releases, don't want to put it to stress :)

I hope the @code team will find a workaround before the fix is released as stable then (see https://github.com/Microsoft/vscode/issues/57803).

**Comment by Tyriar** [comment]
@warpdesign well the workaround is to upgrade to conpty which is blocked on Electron 3 which we're aiming for January currently https://github.com/Microsoft/vscode/issues/52629

**Comment by Stanzilla** [comment]
@zadjii-msft what are the chances of shipping important fixes like this in a cumulative update?

**Comment by zadjii-msft** [comment]
@Stanzilla Effectively none. There's very little chance that we ship any console bugfixes downlevel.

**Comment by doxxx** [comment]
> Effectively none. There's very little chance that we ship any console bugfixes downlevel.

This really needs to change.

**Comment by SYNTAG** [comment]
It's still an issue for me. @Tyriar mentioned that it will be available to us 3-4 weeks from Oct 15, but it's been long past due https://github.com/Microsoft/vscode/issues/57803#issuecomment-429972150

**Comment by Stanzilla** [comment]
Please reconsider your downlevel merge policy, you can't expect people to use Insider builds on production machines and this is a super annoying issue.

**Comment by ericblade** [comment]
Can anyone confirm that this is fixed in WinPTY, in Insiders?  Code team has closed their entry on it because they are moving to the new API, but that isn't going to change the other 40 years worth of software that is no longer doing the right thing visually.  :-)

I realize that no one is going to want to throw out a visual fix to the release tree on a bug fix, but i'd at least like to know if it'll be fixed for the next windows update (March?)

**Comment by Tyriar** [comment]
> It's still an issue for me. @Tyriar mentioned that it will be available to us 3-4 weeks from Oct 15

@SYNTAG pretty sure I didn't do that.

**Comment by SYNTAG** [comment]
> > It's still an issue for me. @Tyriar mentioned that it will be available to us 3-4 weeks from Oct 15
> 
> @SYNTAG pretty sure I didn't do that.

Whoops, my honest mistake. Meant to quote the user above. Edited my comment.
