### ISSUE TITLE
docker-machine ssh shows raw escape code buffer in cmd

### ISSUE THREAD

**Issue by Biswa96** [Microsoft/console#336]
*Windows build number: Version 10.0.18305.1000]
* Command used: `docker-machine.exe ssh docker-host` which uses Go-lang implementation of `ssh` in `docker-machine.exe`.
* What's wrong / what should be happening instead:

  - In CMD:

![cmd-docker-ssh](https://user-images.githubusercontent.com/31443074/50550013-c5cd5100-0c8d-11e9-8463-cb1923be5940.PNG)

  - In WSL:

![wsl-docker-ssh](https://user-images.githubusercontent.com/31443074/50550015-ce258c00-0c8d-11e9-8ef1-d68a4a0c6436.PNG)

I don't know if this is _by-design_ or not. Or may be I should use terminal or not. If you need more information just ask.

**Comment by DHowett-MSFT** [comment]
It looks like `docker-machine` is not setting `ENABLE_VIRTUAL_TERMINAL_PROCESSING` on the console output handle. That'd be a good issue to raise on either docker-machine or the Go library they're using for terminal output.

WSL ssh works, of course, because WSL sets `ENABLE_VIRTUAL_TERMINAL_PROCESSING`.

**Comment by Biswa96** [comment]
@DHowett-MSFT Found another [question](https://superuser.com/q/1386570/726810). Is this in same category of mine?
