### ISSUE TITLE
Supporting all system-installed fonts

### ISSUE THREAD

**Issue by rextheleopard** [Microsoft/console#341]
Windows 10.0.18309 x64

There is popular font [Terminus](https://sourceforge.net/projects/terminus-font/files/). That font does not recognize by windows console, but [ttf fork](http://files.ax86.net/terminus-ttf/) works ok. Any others software recognize [this font](https://sourceforge.net/projects/terminus-font/files/) as monospaced font and supports it. [ConEmu](https://conemu.github.io/) supports it too.

So, maybe it's time to remove this shitty fonts limitations at all and rewrite like in [ConEmu](https://conemu.github.io/)?

Windows console does not support [terminus font](https://sourceforge.net/projects/terminus-font/files/):

![winconsol](https://user-images.githubusercontent.com/26321641/50729166-036a2800-112d-11e9-8ffc-7de9f724801f.png)

[ConEmu](https://conemu.github.io/) supports all fonts, monospaced highlighted.

![conemu](https://user-images.githubusercontent.com/26321641/50729163-f4837580-112c-11e9-9d38-bd9b312d948f.png)

 #295

**Comment by DHowett-MSFT** [comment]
Hi @rextheleopard,
Thanks for reporting this! It looks like #295 contains all the information relevant for this issue, so I'm going to close this one as a duplicate. Couple points, though:

> "shitty fonts limitation"

First, there's a long list of legacy reasons we filter the fonts down the way we do. There's some more info in 295 as to why that's the case, and _exactly [what metrics](https://github.com/Microsoft/console/issues/295#issuecomment-433589611) the fonts you're trying to use must declare_ in order to be visible.

> #295

Second, it will suffice in the future to use the thumbs-up reaction and subscribe to indicate your support for an existing issue; no need to file another one! The first one definitely has our attention.

Thanks again!
