### ISSUE TITLE
Cursor shape not preserved in PowerShell

### ISSUE THREAD

**Issue by wigster** [Microsoft/console#409]
* Your Windows build number:  10.0.18362.53

* What you're doing and what's happening: 
Open PowerShell (5.1.18362.1)
Set cursor shape to Solid Box (or any other non-legacy)
Cursor is solid
Execute command (e.g. cd, ls )
Cursor is back to legacy shape

CMD or WSL bash work as they should

* What's wrong / what should be happening instead:

Cursor shape should stay fixed.

**Comment by zadjii-msft** [comment]
If you do a `Remove-Module PSReadline`, then Powershell works as expected. I believe that this is a bug in their code, so I'll point you at [lzybkr/PSReadLine](https://github.com/lzybkr/PSReadLine) to file the issue on them.

The root cause is that calling the `SetConsoleCursorInfo` API will reset the console's cursor size to whatever they've requested in that API call., and that it's currently not possible to set cursor shapes with that API.

**Comment by LinuxOnTheDesktop** [comment]
Same here. Windows 19 1909.

**Comment by 8192bits** [comment]
For anyone still hitting this in 2026 on conhost with PowerShell 5.1 or 7.x,
I patched the PSReadLine 2.0.0 and 2.4.5 DLL directly to fix this by re-emitting
the ANSI cursor sequence in ReallyRender() after CursorVisible is restored.

[CursorShape](https://github.com/8192bits/CursorShape)

**No recompilation needed. drop the DLL, set up $PROFILE, done.**
**Providing persistent cursor shape.**

Feedback welcome.
