### ISSUE TITLE
can't see file whitch create by explorer.exe using 'ls' in wsl bash

### ISSUE THREAD

**Issue by wengzuyang** [Microsoft/console#43]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.125]

* What you're doing and what's happening:  
Using explorer.exe create a new file to "C:\Users\Administrator\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs/opt"，then using bash to 'ls' it .
![image](https://user-images.githubusercontent.com/11473283/34324068-21755e4a-e89e-11e7-8a82-e0e88595d392.png)

* What's wrong / what should be happening instead: can't see this file in bash.
![image](https://user-images.githubusercontent.com/11473283/34324070-55ebbda4-e89e-11e7-9132-1df583f70072.png)

**Comment by khouzam** [comment]
Hi @wengzuyang

This isn't really an issue with the console but with WSL and is by design as described in [this blog post](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/) on how the WSL filesystem works. The following paragraph explains the problem.

Interoperability with Windows

While VolFs files are stored in regular files on Windows in the directories mentioned above, interoperability with Windows is not supported. If a new file is added to one of these directories from Windows, it lacks the EAs needed by VolFs, so VolFs doesn’t know what to do with the file and simply ignores it. Many editors will also strip the EAs when saving an existing file, again making the file unusable in WSL.

Additionally, since VFS caches directory entries, any modifications to those directories that are made from Windows while WSL is running may not be accurately reflected.

**Comment by wengzuyang** [comment]
It explains the matter,thanks.
