### ISSUE TITLE
Official API to create a third-party console host (like pty in Unix)

### ISSUE THREAD

**Issue by be5invis** [Microsoft/console#57]
Yes, a full, comprehensive pty API. It should be able to handle all kinds of console applications that run in Conhost (WSL, Win32, UWP, even 16-bit DOS programs).

**Comment by zadjii-msft** [comment]
I've definitely heard this ask more than a few times before.

"Official pty API for Conhost" does seem like a bit of a broad feature request. I'm not saying that it's totally impossible, but lets entertain the hypothetical for a bit here.

If I were to go about implementing this, what would be the most important things for me to implement? What kind of surface would this API have? How would you expect it to behave?

**Comment by be5invis** [comment]
Well you know, CONHOST internally has a char matrix that places all the characters. So the API should output such things without opening a CONHOST window.

**Comment by parkovski** [comment]
My wishlist for this feature:
- Provide a way to create a pair of console handles without going through conhost.
- <s>Document</s> "implement" a function, let's call it ConsoleControl, that lets you generate the events a console client would expect to receive.
- Make WSL tty interop handles translate to these.
- Document what kind of black magic you have to use to make cmd.exe respond to a ^C.
Bonus for 3rd party console authors: an official way to set these handles as "this process' console" so when someone calls AttachConsole it works.

**Comment by bgshacklett** [comment]
It would be really good to get some input from the authors of terminal emulators like Maximus5/ConEmu and zeit/hyper.

**Comment by parkovski** [comment]
Cc: @Maximus5, not sure of a good contact from hyper.

**Comment by Maximus5** [comment]
It's a real pain to implement ConEmu via official console API. I have to use detours to hook almost all available functions. And what for? Linux provides pty functions and signals for decades and they have many terminals for any taste.

**Comment by bgshacklett** [comment]
@zeit and @chabou appear to be the most active on Hyper. Also, @Eugeny has the Terminus project.

**Comment by Eugeny** [comment]
Both Hyper and Terminus use node-pty as a PTY backend, which in turn uses the winpty project to provide a pty API on Windows, which is basically a ton of black magic that runs a hidden conhost window and reads its contents.
Having an API identical to the POSIX pty controls would allow cutting the amount of code in node-pty in half and dropping winpty.

**Comment by parkovski** [comment]
The hooking issues are why I think this is important. I don't think it's even possible to create console handles without opening a conhost window. You can't even make a custom driver that acts like a console without hooking all the APIs.

I think it's great that the built-in console window is improving, but it shouldn't be this hard and hacky to implement a third party terminal. I don't think the exact shape of the API is that important, because if the functionality is there somebody will make a pty wrapper API.

In my opinion, this (for tmux) and a sudo command that doesn't go through UAC are the last pieces I need to make the Windows console the dev environment I want. I'm not familiar with the headless Windows server, but I'd imagine these things would be pretty important there too.

**Comment by yatli** [comment]
@be5invis does the pty features conflict with the legacy console? If not, we can regard the features as an "extension". For example, report terminal type as "VT-MSCMD" which allows things like, actively changing the size of the window. In this way both legacy apps (which ignore the PTY stuff) and the terminal bits will be happy.

**Comment by parkovski** [comment]
The implementation has changed a lot since then - the console window used to live in csrss, which is why it missed out on theming. There's a good overview of this [here](https://github.com/rprichard/win32-console-docs), but basically whenever a console subsystem program is launched or you call `AllocConsole`, csrss creates a new connection to the console driver and passes the handle to `conhost.exe`.

Conhost is now a regular user-land program, it's just blessed with the ability to be given new console handles and an API that we don't have. When I run WinAPIOverride on it, I see a bunch of calls to DeviceIoControl (undocumented flags) and ConsoleControl (undocumented function). The rest of the console APIs look like they call NtDeviceIoControlFile directly. If we could create new console handles and use these APIs without going through conhost, I think we'd have what we need to make a Unix pty wrapper. Basically, I think the functionality is there, it's just not exposed to anyone other than conhost right now.

**Comment by zadjii-msft** [comment]
Hey all,

I just want you to know that we're definitely going to be CLOSELY following this discussion. A "PTY Implementation" is one of the highest items on the backlog, and it will likely be one of the most important things to get right the first time. 

What I'm getting from this discussion:
 * Be able to create a "headless console" to host client commandline applications (cmd, bash, etc) 
 * Be able to specify an input and output handle to be able to write input to this console, and read buffer contents
   - Important to be able to send Ctrl+C as a SIGINT to the client application
   - be able to send resizes to this console and receive them via some mechanism (another handle? in band with the input/output?)

Would these things satisfy most people? What am I missing, what could be improved, etc.

**Comment by be5invis** [comment]
It would be good if we could provide a callback as a "layout function," i.e., the API would call this callback function to fill a string into the character matrix. It would be useful for multi-language support since the layout is a hard task.

**Comment by be5invis** [comment]
My requirements:

1. Crating a headless console
2. Read the char matrix -- including character and properties.
3. Send user interactions (key and mouse) to the headless console.
4. Custom layout function (maybe `HRESULT layout(Console *, LPCWSTR, ... `) for advanced i18n.

**Comment by Eugeny** [comment]
@be5invis I think it's important to differentiate between a Pty, which is terminal/layout agnostic and only handles data and extra messages/signals and a terminal, which handles the visual layout.

**Comment by Maximus5** [comment]
@zadjii-msft I think you described proper requirements.
All console API functions (like ReadConsoleInput) shall be able to work with these handles. And Read/WriteConsoleInput shall be able to process all know event types of course.

There is also some craziness with ReadFile called on console handle. In some cases it behaves like ReadConsoleA (returns a line, processing Enter, arrows for history, Tab for completion...), but in other cases it just return ANSI characters one by one. It's hardly possible to find documentation and requirements for console modes ReadFile depends on...

**Comment by zadjii-msft** [comment]
@Maximus5 How would you feel if the input "API" was sane on how it was handled, but didn't support certain keystrokes?

For example, Ctrl-M, Ctrl-J and Enter. Do we really care about differentiating between Ctrl-M and Enter, or would it be okay to map Ctrl-M to Enter (As long as it's documented as such)? They're different keystrokes on the keyboard, sure, but for any *nix style terminals, we can't differentiate those keys.

**Comment by Maximus5** [comment]
@zadjii-msft If we are talking about future *POSIX* PTY API it's OK, because indeed in Unix many keystrokes are mapped to one sequence. Personally I consider this as lack of interface, but compatibility makes the rules.

But proposed API in this topic is supposed to let us ability to implement "third-party conhost" windows. And I believe it must not be limited to neither Unix nor Windows limitations!

By Windows limitations I mean features like

* true color support through ANSI (it's not possible to retrieve info from conhost)
* ability to place cursor after the end of line without going to the next line
* ability to understand where the console is "dirty" (was real output from APP even with spaces)
And so on...

If we (third-party devs) may create *real console handles* which may be used with native console API functions I believe we would be able to implement any emulation type - POSIX or Windows.
I don't want to lose ability to run native console applications...

**Comment by be5invis** [comment]
Clarify the title.
What we need is a real abstraction layer, an API set to let us implement something like a console host, including third party consoles or something like tmux. It does not need to look exactly like Unix pty. Actually it should be stronger than Unix pty, since there are more black Magics in Conhost.

**Comment by yatli** [comment]
@be5invis agree in the title change, that this should be a PTY-like layer. Additionally, I feel that we should separate these two things: 

1. implementing such a layer that 3rd party terminal can allocate real console handles (which is then used in the API surface of this layer)
2. VT emulation, and PTY interface *above* this layer -- this should be just like how the console is used for WSL.

In this way there is no interference between existing windows console apps and the *nix things because the former leverages only 1) and the latter leverages 1) and 2).

**Comment by parkovski** [comment]
A few thoughts on complications:
- If we're supporting "legacy" Windows mode, which I agree is important, how does input get exposed? It seems like `ReadFile` isn't well-equipped to handle that mode. Do we have to switch to `Read/WriteConsoleInput` in win32 mode? Have a second handle for non-text and/or non-ANSI input, and if so is overlapped IO necessary to get input order correct? Do we map things that can be mapped (like colors) to ANSI escapes? What about things that can't? Do we make new escapes for things like `^M` or maybe one escape that says "the next n bytes are an `INPUT_RECORD`"?
- Do we support mapping between the two modes? E.g. when we get tmux on Windows, how do we handle tmux being in ANSI mode, communicating with a child process in Windows mode? This also comes into play with WSL interop - what happens if we get an interop handle and then try to change the mode?
- What about signals other than SIGINT? Thinking mainly about suspend/resume right now which is already supported by conhost, but also later on with interop, how do we translate WSL signals?
- We don't have terminfo, so we probably need to be really clear on how a conforming implementation behaves.

**Comment by zadjii-msft** [comment]
I do want to make a note, whatever we end up implementing is going to allow existing client applications to continue using the full Win32 console API, and ideally it's going to be without forcing 3rd party terminals from implementing the entire console API surface themselves. We'd love to hide the "black magic", and expose only a sane surface to implement on top of.

<sup> P.S. This discussion is my favorite of all of them, a lot of good thoughts in here.</sup>

**Comment by Tyriar** [comment]
Just echoing @Eugeny's thoughts; this would both greatly simplify and improve the stability of the terminal within VS Code, or where ever [node-pty](https://github.com/Tyriar/node-pty)/[winpty](https://github.com/rprichard/winpty) is used. Currently there's no way forward for many of the VS Code terminal Windows issues due to the way it's implemented. A proper pty API (with legacy emulation on conhost's side) would have massive impact.

**Comment by parkovski** [comment]
Expanding on my first two points a bit -
I think the best way to go would be to map everything that can be mapped to ANSI on the PTY host side, and however the other input gets exposed, it should be opt-in, but extending, not replacing the ANSI input. Doing it this way has these advantages:
- Writing a PTY host is less complicated - you don't have to worry about modes.
- Linux code is more or less immediately portable. Once you're ready to handle the extra stuff, you can opt in.
- Easy (easier?) to implement WSL interop on top of this.

If it's possible to make things work without any filtering though, that'd be even better. iTerm uses a double escape to represent the Option key I think, so I think there is some precedent to add sequences for platform-specific things.

**Comment by Maximus5** [comment]
I don't think that implementing the proposed API in ANSI way is good idea. It's rather bad choice for Windows I believe.

* Input: You can't pass keypresses without losing information, e.g. do you know how many keypresses may be encoded by `\0` character? It's not ideal in WinAPI because of indistinguishable `Shift` key, but WinAPI is more rich.
* Output: You can't properly map WinAPI calls to ANSI. WinAPI console applications may operate with full console buffer, Linux style applications may write only *to the visible part of the buffer*.
* ANSI calls may be easily translated to WinAPI functions, as ConEmu is doing.

I vote for conhost-like API, just let some handles acts as native console handles, it would be enough to implement both POSIX and Windows interfaces.

**Comment by parkovski** [comment]
I’d be fine with that, my only concerns are that a PTY wrapper can be written that allows porting Linux programs (basically I want to see tmux on Windows), and that the wrapper works regardless of the client mode.

I do agree that ANSI is not the best fit for the Windows functionality. It’s kind of an unfortunate standard IMO, but a standard nonetheless.

**Comment by be5invis** [comment]
cc. @rprichard

**Comment by be5invis** [comment]
@parkovski I think we should do this:
- MSFT provides a very "Windows"-flavored API (like a lot of COM components...), covering every single feature needed to implement a console host. CONHOST itself could be also rewritten to be built over this API.
- You guys write a wrapper over it, to make it "looks like Unix PTY".

**Comment by be5invis** [comment]
@zadjii-msft Does console do something special when it is running a 16-bit program via NTVDM? And does CONHOST still has mouse support now?

**Comment by zadjii-msft** [comment]
@Maximus5 
> * Output: You can't properly map WinAPI calls to ANSI. WinAPI console applications may operate with full console buffer, Linux style applications may write only to the visible part of the buffer.

Out of curiosity, how many applications really utilize that part of the console API? It would really seem to me that writing to the part of the buffer outside of the viewport isn't all that useful. 

---
@be5invis 
> Does console do something special when it is running a 16-bit program via NTVDM? And does CONHOST still has mouse support now? I remembered in the old days I programming Turbo Pascal on Windows XP the console has mouse support, in both windowed and full-screen.

I'm fairly certain the NTVDM support was removed from conhostv2, or at least before my time on the console team, so unfortunately I don't really know. I know there are/were a bunch of references to NTVDM specific functionality in the codebase, but I believe they're all commented out or unimplemented now.

The console API has had mouse events available from ReadConsoleInput since time immemorial (I believe) and we added support for mouse input via VT since Creator's Update (I think - whichever release we added RGB support added mouse support as well).

---
> (basically I want to see tmux on Windows)

Believe me, so do I.

**Comment by Maximus5** [comment]
@zadjii-msft

> how many applications really utilize that part of the console API? 

I can't count these applications. For sure the Far Manager reads and writes full console buffer.
Personally I don't think this functionality is required for console applications, but I know it is used. For example some Unix ports (cygwin/msys) read buffer and write it back while switching no-scroll modes.

In fact these differences between Unix and Windows terminals (full buffer addressing, cursor position beyond EOL without line feed, ...) are really confusing.

**Comment by be5invis** [comment]
@maximus5 @zadjii-msft 
A diagram is better than thousands of words
```
BEFORE

Console apps ---- NT Kernel ---- CONHOST ---[Black Magic!]--- Conemu, VSCode, etc

AFTER

Console apps ---- NT Kernel ---- Console Host API ---- CONHOST
                                         |
                                         `------------ Conemu, VSCode, etc
```

**Comment by parkovski** [comment]
A couple more thoughts/questions:

How are we addressing overlapping functionality? Colors, mouse and keyboard input, scrolling, clear screen - these all have traditional APIs and ANSI escapes to set them. Do we have to implement both? I don't really like that idea, but I also don't like the idea of automatically converting to one or the other. I have a couple ideas and am interested in thoughts on this:
  1. Provide a mapping API, something like `AnsiEscapeToConsoleMessage`/`ConsoleMessageToAnsiEscape`, and then let the host choose if they want to implement both APIs separately or just go with the standard mappings.
  2. Bundle input messages with the text that triggered them - if we have a theoretical `CONSOLE_MESSAGE` struct, it would contain a span pointing to the input buffer if an ANSI sequence caused the message, or null if the message was generated by the console API.
  3. A better way to handle this?

In either case these would respect the mode, so a handle not in VT mode wouldn't generate ANSI->message mappings. Personally I think (1) is more flexible.

Last thing, maybe not strictly in scope here, but once this is in place, it'd be nice to be able to override which app opens when you start a console subsystem exe or call `AllocConsole`, although I can definitely see some concerns around this. Maybe a developer mode only feature?

**Comment by yatli** [comment]
@be5invis does this make sense to you:

```
Console Host API ----- CONHOST:        Stock frontend GUI, full ConsoleAPI access, backward-compatible limited ANSI esacpes
        |
        |`------------ Conemu,VSCode:  Alternative frontend GUIs, same capability with CONHOST
        |                              libPty-agnostic, because libPty-[draws to]->ConsoleAPI-[send message to]->FrontEnd
        |                              WSL-agnostic, because WSL-[libPty/ConsoleAPI]->ConsoleAPI-[send message to]->FrontEnd
        |
        |`------------ libPty:         Use ConsoleAPI to draw into a console like a canvas. Just like how we would use libvt
        |                              to paint the content of a terminal into a GUI framekwork (WINAPI, Qt, etc.)
        |
         `------------ WSL:            Wraps around libPty when running Linux code. Calls ConsoleAPI when running Windows apps. 
                                       Blocks access to pty interface when Windows app calling ConsoleAPI is running.
                                       When Windows app finishes, notify libPty to update state accordingly, and then unblock pty access.
```

@parkovski in my mind there should be no conversion. Everything going into ConsoleAPI is ConsoleAPI (console messages, limited ANSI). pty stuff is just a rendering library.

**Comment by yatli** [comment]
to clarify a bit, by "rendering" I mean how to draw into CONHOST so that it would look like it's drawn in a VT -- not how fonts are bitblit into graphics window buffer.

**Comment by Maximus5** [comment]
@yatli What is the difference between "limited ANSI" and "libPTY"? ANSI processor have to be implemented in terminal (conhost, ConEmu, etc.) but not in some third-party libraries. ANSI standard is terminal-dependent, and there are tools like terminfo to determine the standard. AFAIK conhost (and ConEmu) are close to xterm standard.

@parkovski ANSI have to be processed by terminal. There are vital sequences that ConEmu requires to implement features.

**Comment by be5invis** [comment]
@parkovski The purposed API would not contain anything related to ANSI — It is provided in the pure Windows flavor, and if you want ANSI, you could write a wrapping layer over it to convert back to ANSI.
The "Console Host API" should cover **EVERY** feature needed to implement the stock CONHOST (v2). However, the Kernel and API could provide a special mode that passes through the ANSI sequences instead of interpreting them internally.

**Comment by be5invis** [comment]
Two diagrams:

 - Control-only mode
```
Client application ---[WINAPI]--- Console Host API ---[Some internal form]--- Third-party terminal
                  `---[ANSI]----'
```
 - ANSI-passthrough mode
```
Client application ---[WINAPI]--- Console Host API ---[Some internal form]--- Third-party terminal
                  `---------------------------[ANSI]--------------------------'
```

**Comment by yatli** [comment]
@Maximus5 by "limited ANSI" I actually mean "what is supported as of now, in the current CONHOST". From the `terminfo` point of view the current `CONHOST` should be close to a `dumb term`, not `xterm` because it does not understand most (if not all) escape sequences. There are also packages trying to intercept ANSI sequences and translates to what CONHOST understands through WINAPI, but not feature-complete, thus my "limited" part.

Also, I think we do can implement ANSI processor in a library, and let a frontend like ConEmu stick to what the ConsoleAPI requests to present. Thus, a pty-based program can be handled with no difference to existing Win32 program.

For example, `terminfo` is just a series of probe sequences that the program sends to the terminal, to determine its capabilities. With barebone ConsoleAPI most stuff should fail because it does only very limited stuff. But if we pipe the program to libpty, then it should be able to simulate whatever libpty is instructed to simulate -- for example, even to display SIXEL images, perform vector drawing, etc. Of course, to really make an image to be displayed, libpty should find a way to talk to ConsoleAPI, and thus sending the images to the frontend in a well-defined manner, which is currently absent -- just an example, but the same should apply when `terminfo` is piped into `libpty`, and the answer gets back to `terminfo` without even letting `ConsoleAPI` know -- because `ConsoleAPI` is `ConsoleAPI`, it's not `vt100`, it's not `xterm`, and `libpty` should know how to translate things to render whatever simulated terminal properly with `ConsoleAPI`.

**Comment by yatli** [comment]
From the `ConEmu` point of view, I guess you're probably thinking about this:

If you want to implement features dependent on the ANSI standard, rather than to stick to what the ConsoleAPI instructs it to display -- my aforementioned approach is not complete. We will need to additionally link `ConEmu` with `libpty`, so that the raw ANSI sequences are tee'ed to `ConEmu`. Then it's worrying whether the tee'ed information interpreted by `ConEmu`, and that interpreted by `libpty`, can be kept in sync.

But on the other hand, what if `libpty` completely understands xterm so that the console messages sent back to `ConEmu` fully replicates what is drawn on the equivalent terminal? Maybe we should take a look at the implementation of other terminals, for example, `qtermwidget`: https://github.com/lxde/qtermwidget/blob/master/lib/Emulation.h

In their implementation, the job of actual ANSI sequence processing is delegated to a "backend" implementing what `Emulation.h` specifies.
One is then free to choose a pty library to do the real work, for example, with `vt102`: https://github.com/lxde/qtermwidget/blob/master/lib/Vt102Emulation.cpp

If I understand this correctly, suppose we have our `libpty` in place, we can use it as a drop-in replacement for vt102, and thus bridge the Qt frontend to ConsoleAPI. The same workflow can be done for `ConEmu`. Now the question is whether it'd be sufficient to implement a feature specific to ANSI escape sequences, based on what `Emulation.h` provides?

**Comment by Maximus5** [comment]
I still think that mixing of emulation layers (ConsoleAPI with ANSI) is a wrong approach.
* ConEmu implements some [specific sequences](https://conemu.github.io/en/AnsiEscapeCodes.html#ConEmu_specific_OSC) and several are crucial to some features like prompt selection or CWD processing.
* Some ANSI don't have analogues in WinAPI and I doubt we must implement them in ConsoleAPI: CWD, icons, tab colors, etc. It's easy to implement new ANSI sequence, but it's a pain to create and deploy new API function.

I believe the terminal must process all ANSI and just skip unknown sequences. That's the Unix way which all known terminals follow. Please don't try to create more layers - more problems.

**Comment by yatli** [comment]
I think I understand your point. It does not conflict with what I presented, because it implies that you are implementing terminal emulation yourself, and ConsoleAPI just appears to be ConsoleAPI alone, with no knowledge about the escape sequences -- which is totally fine.

**Comment by yatli** [comment]
My concern is, it's not that we create more layers -- more layers will be there anyway.
Consider this:
```
ConEmu
      `-tmux, the "layer"
             `-cmd.exe, calling ConsoleAPI
```

**Comment by parkovski** [comment]
@Maximus5 What I was suggesting with the translation APIs is more like a terminfo equivalent - it shouldn't happen automatically and it shouldn't be required for a terminal to use them. My intention is that it's a conhost compatibility thing - it gives you a way to ask how exactly would conhost handle certain escapes. How I imagine it would be used is something along these lines:
```c
if (AnsiEscapeToConsoleMessage(escapeString, &message)) {
    // message represents whatever action conhost would take here.
    // You are not required to do the same thing, but if you want strict conhost compatibility, this is how you achieve that.
} else {
    // Handle any other additional escapes for your terminal here
}
```

I still intend that we would see exactly what conhost sees and can interpret it however we'd like. I wrote ANSI escape handling for PSReadLine on Windows, and had to do a lot of trial and error - press a key and see what gets generated. Basically I just want to avoid this scenario.

**Comment by zadjii-msft** [comment]
You're absolutely right, a picture is worth 1000 words. I think that @yatli has so closely hit the nail on the head, (and someone finally noticed the 17618 release notes), that I can't help but share some more thoughts. 

Now, what if we had something like this:
```
      +------------------+    +----------------------+
      | Terminal         |    |                      |
      | Application      |    | Client Application   |
      |                  |    | (cmd.exe)            |
      +-----------+--^---+    +-----------^----------+
Communication via |  |                    ||Communication over
pipes (using VT)  |  |                    ||Win32 API
                  |  |                    ||
      +-----------v--+---------------------v---------+
      |                   Conhost                    |
      |Render console to VT <------+Traditional Win32|
      |Synthesize input from VT |-->functionality    |
      +----------------------------------------------+
```

So a client application that only knows about how the Win32 world works would still communicate with a conhost via the API, but a terminal application could be written to read conhost state via VT and write input to the host via VT.


I've been holding my cards a little close to the chest for the course of this discussion. **We've actually been working on this functionality since the start of RS4**. As of [Insiders 17618 ](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17618), we're actually using this functionality to power WSL interop.

![image](https://user-images.githubusercontent.com/18356694/37308260-b7399a4c-25fa-11e8-9780-960ba68400ef.png)

### What does this mean to this discussion

The feedback in this thread has been incredibly helpful, and I'm definitely not closing this thread. The functionality is NOT ready for public consumption yet - we're still working out a lot of bugs in it. Take this as a warning - don't take dependencies on anything in Insiders quite yet. We're still working out how to formalize what we have into a proper API.

**Comment by be5invis** [comment]
@zadjii-msft So does the “VT” between terminal and CONHOST cover all the functionalities that WIN32 have? @Maximus5 have pointed out that ANSI is insufficient.

**Comment by zadjii-msft** [comment]
@be5invis Yes, ANSI is insufficient, which is why the VT emitted isn't recreating the API calls, it's recreating the state of the buffer. @yatli pretty much called it - we just "render" the conhost state using VT. Anyone with a VT parser should be able to then recreate the conhost's state.

Which does bring us to limitations (that I mentioned before) - the conhost acting as the pty will have it's buffer locked to the viewport size. There was no other way to make consumers able to accurately represent the buffer contents.

**Comment by be5invis** [comment]
Could we design some ANSI extension to bring back the full compatibility? Just like how the Linux guys supported 24-bit colors.
Or add another API to let us grab the raw buffer/do custom layout.

发自我的 iPhone

在 2018年3月14日，01:25，Mike Griese <notifications@github.com<mailto:notifications@github.com>> 写道：


@be5invis<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbe5invis&data=02%7C01%7C%7Cb5ea48663b0845df097f08d5890774d5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636565587468814756&sdata=aabMP0kDrAWLYP%2F0X0KXjxaKxVbBH7DQ0NoyyRPYDO8%3D&reserved=0> Yes, ANSI is insufficient, which is why the VT emitted isn't recreating the API calls, it's recreating the state of the buffer. @yatli<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyatli&data=02%7C01%7C%7Cb5ea48663b0845df097f08d5890774d5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636565587468814756&sdata=LHZho3Xa8vuNBggDZKuAsNhK%2BXk4kKYwFrAE9UMtohA%3D&reserved=0> pretty much called it - we just "render" the conhost state using VT. Anyone with a VT parser should be able to then recreate the conhost's state.

Which does bring us to limitations (that I mentioned before) - the conhost acting as the pty will have it's buffer locked to the viewport size. There was no other way to make consumers able to accurately represent the buffer contents.

**Comment by Tyriar** [comment]
> Which does bring us to limitations (that I mentioned before) - the conhost acting as the pty will have it's buffer locked to the viewport size.

But this is fine isn't it? The pty API would be used to bring VT terminals to Windows which already have this restriction?

**Comment by zadjii-msft** [comment]
@Tyriar that's exactly correct. If we're gonna talk about extending VT to create Windows-specific sequences, that'll be a totally other discussion that we're not going to be really pursuing for the time being.

**Comment by joelhandwell** [comment]
@jwilm not sure if you have any opinion in relation to https://github.com/jwilm/alacritty

**Comment by zacps** [comment]
I've been working on windows support for alacritty. At the moment we just use winpty (Like everyone else it seems) but a native API would be great.

I don't think I have much specific feedback on the API design as it seems like everything has been pretty well thought through already.
The only thing I'd say is that it would be nice if the API provided a single R/W pipe (à la the unix pty) rather than winpty's dual read and write pipes.

**Comment by yatli** [comment]
> @Tyriar that's exactly correct. If we're gonna talk about extending VT to create Windows-specific sequences, that'll be a totally other discussion that we're not going to be really pursuing for the time being.

Exactly. Extending VT leads to `VT-CONHOST` standard and will be a total new thing. Pretty exciting idea but there shall be dragon ahead.

**Comment by onomatopellan** [comment]
I think this will be of interest to the thread 🐱‍💻

> build 17711 has new functions in kernel32: CreatePseudoConsole/ClosePseudoConsole/ResizePseudoConsole

https://mobile.twitter.com/h0x0d/status/1015398241263685632

**Comment by zadjii-msft** [comment]
Hey good eye! Looks like they've made it out into the wild, though I should probably make it abundantly clear:

**HERE BE DRAGONS**

We're still in the Insider's phase of the API, and I'm 100% sure what's in the current release won't work correctly. We have a couple bugfixes that are still bubbling up and out that fix some critical bugs with the API. So I'd maybe wait a few weeks before trying it out ;)

**Comment by DarthSpock** [comment]
This will be of interest to @mintty.

**Comment by mintty** [comment]
Thanks for the hint, but, admittedly not having studied the details, "pty API" sounds like you would have to adapt applications so can run in a pty-like environment in a terminal application, right?
If that's the plan, it does *not* help mintty, sorry, because it's not backwards-compatible with existing applications. What would help, and would probably be much easier, is if it were possible to hook into the group of WriteConsole functions, and to inject such a hook from a bridge app (conhost-based?) like wslbridge.

**Comment by be5invis** [comment]
I do not think any existing WIN32 apps need to be modified to run under PTY. Though there might be hidden weird issues (like measuring text’s width or DBCS support).

发自我的 iPhone

在 2018年7月11日，05:53，mintty <notifications@github.com<mailto:notifications@github.com>> 写道：


Thanks for the hint, but, admittedly not having studied the details, "pty API" sounds like you would have to adapt applications so can run in a pty-like environment in a terminal application, right?
If that's the plan, it does not help mintty, sorry, because it's not backwards-compatible with existing applications. What would help, and would probably be much easier, is if it were possible to hook into the group of WriteConsole functions, and to inject such a hook from a bridge app (conhost-based?) like wslbridge.

**Comment by parkovski** [comment]
@mintty This would take the place of winpty or wslbridge - allows you to act as conhost without any hacks or workarounds. The console apps on the other end don't have to be modified, just the terminal app taking the place of conhost. Presumably `CreatePseudoConsole` will give you an input and output handle; pass those to a console process and whatever you write to the input it will see in its stdin, and when it writes to the output, you can interpret & display however you want.

**Comment by DarthSpock** [comment]
How much easier does this make native `conhost` able to perform proper VT sequences and display UTF-8 chars (vice the legacy UTF).  It sounds like it would ensure far faster procurement of new features (such as emojis and Sixel support). If this is the case, then I would think terminal apps like Konsole (which I highly desire to be available on Windows) would be even more easily ported to Windows. Though that would be a bit strange to see a `cmd.exe` running inside Konsole (not that I'd complain). What would be funnier is if somebody ported Iterm2 to Windows using the API. Sounds like everything that's needed is in place afterall (minus the critical bugs you're squashing).

**Comment by miniksa** [comment]
@DarthSpock, the latter half of your post there about being able to port other terminals that natively speak VT to Windows is something that should be very possible here when we round all the sharp edges off the feature.

As for `conhost.exe` itself displaying new things.... that's not super changing here. It's technically capable internally now of holding a lot more stuff within the Unicode planes than it was before to help enable this functionality (big points to @adiviness for working on this part!), but we haven't been able to make `conhost` display all of them correctly on its own surface yet. We need a renderer overhaul for that.... which is on our backlog. That's when you'd see emojis for sure and maybe... MAYBE sixels... show up on `conhost's` window itself.

Our major focus here has been to engineer a platform that is capable of servicing the content needed by others to "make terminals great again" on Windows. We're the only ones who can change the OS to enable others to succeed in this way, so that's been our focus this release. Making our inbox terminal surface great in `conhost` is something we'd love to do too.... but there are a lot of great terminals out there and we have limited resources. So we're trying to unblock the world first in a way that only we can and we'll assuredly turn our eyes back to our own terminal surface again in the future.

There's a pending blog post from us to explain what we've done here for this release that should include some of these details and what it is capable of and what it is not capable of. @bitcrazed already has a draft of the post in our inboxes for review. We're currently sassing him about the diagrams and some of the wording, so it will take a little more time before it rolls out.

I recommend you watch https://blogs.msdn.microsoft.com/commandline/ for our posts on the Windows Command-Line to find out more. Rich has really started to get the flywheel moving on pushing blog posts out. The devs are also chomping at the bit to start sharing some more of our workings with you via that platform as soon as we get the boilerplate series of articles out.

And I promise you we'll get to filling out docs for this at https://docs.microsoft.com/en-us/windows/console/ in the next few months. We're just at the peak of bug bashing time right now. When bugs slow down, we will spend more time on writing up the detailed documentation. We wish we had more hours in every day! Thanks for your patience and interest!

**Comment by zadjii-msft** [comment]
@DarthSpock 
> Though that would be a bit strange to see a cmd.exe running inside Konsole 

xterm close enough for you?
![image](https://user-images.githubusercontent.com/18356694/42586841-d39a25f6-84ed-11e8-98a1-a21fb08d758d.png)

No? Maybe you want to set your default shell in `gnome-terminal` to `cmd.exe`?
![image](https://user-images.githubusercontent.com/18356694/42586977-3fef8868-84ee-11e8-8b88-eef438e6895a.png)

**Comment by DarthSpock** [comment]
That's totally understandable and think it's great what you've done! I'm just thinking there will be environments where even with this API, ported terminals may not be available (authorized) for download so if it can be leveraged for native conhost, that would be great news as well. 

I always keep on eye on the commandline blog for new posts and have been following along the console series (which are great btw). Looking forward to seeing the docs updated. Enjoy the bug bashing!

**Comment by DarthSpock** [comment]
@zadjii-msft Nice! Definitely strange to see but not in a bad way.

**Comment by bitcrazed** [comment]
I have two new [posts in this series](https://blogs.msdn.microsoft.com/commandline/2018/06/20/windows-command-line-backgrounder/) in-progress as I type :) Firsts discussing Console Internals is nearing completion. The next talks PTYs. Stand by ;)

**Comment by Tyriar** [comment]
The blog post announcing "ConPTY" went out 🎉  https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/

**Comment by bitcrazed** [comment]
Thanks @Tyriar - AT LAST, right? ;) 

And with the public announcement of ConPTY API in current Insiders builds, and coming to this fall's release of Windows 10, I am closing this issue.

Thanks for your patience everyone ;)
